shallow_clone: true
version: '{build}'
skip_tags: true
os: Visual Studio 2015
platform: x64
install:
  - ps: Install-Product node Stable x64
  - npm uninstall --save-dev @shinnn/eslint-config-node eslint istanbul
  - npm install
build: off
test_script: node --strong_mode test.js
