shallow_clone: true
version: '{build}'
skip_tags: true
install:
  - ps: Install-Product node Stable
  - npm install
build: off
test_script: node --string_mode test.js
cache: node_modules -> package.json
